# Generated by Django 3.0.5 on 2020-05-22 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forex', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='margin',
            field=models.FloatField(default=20, null=True),
        ),
    ]
