# Generated by Django 3.0.6 on 2020-05-22 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forex', '0003_auto_20200522_0812'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.AddField(
            model_name='profile',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
