# Generated by Django 3.0.4 on 2020-05-25 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forex', '0004_auto_20200522_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='amount',
            field=models.FloatField(default=20, null=True),
        ),
    ]
